erDiagram
  MEDICAL_FORMS {
    INTEGER id PK
    DATETIME created_at
    VARCHAR servicio_salud
    VARCHAR establecimiento
    VARCHAR especialidad
    VARCHAR unidad
    VARCHAR nombre
    VARCHAR historia_clinica
    VARCHAR rut
    VARCHAR rut_padre
    VARCHAR sexo
    VARCHAR fecha_nacimiento
    VARCHAR edad
    VARCHAR domicilio
    VARCHAR comuna
    VARCHAR telefono1
    VARCHAR telefono2
    VARCHAR correo1
    VARCHAR correo2
    VARCHAR establecimiento_derivacion
    VARCHAR grupo_poblacional
    VARCHAR tipo_consulta
    VARCHAR tiene_terapias
    TEXT terapias_otro
    TEXT hipotesis_diagnostico
    VARCHAR es_ges
    TEXT fundamento_diagnostico
    TEXT examenes_realizados
    VARCHAR nombre_medico
    VARCHAR rut_medico
    TEXT patologias_ges
  }

  %% Modelo actual no tiene relaciones a otras tablas.

